# Project Euler
# Problem 2
# Even Fibonacci numbers
# - Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#   By starting with 1 and 2, the first 10 terms will be:
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# - By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#   find the sum of the even-valued terms.

# Clear memory before query
rm(list=ls())

# Defines max number
max = 4000000

# while loop to calculate values up to 4000000
currentValue = 1
fullArray = 1

while(currentValue < max)
{
  # If it's first iteration, use 1 else use previous value
  if(currentValue == 1)
  {
    lastValue = 1
  } else{
    lastValue = fullArray[length(fullArray)-1]
  }
  currentValue = currentValue + lastValue
  # Only record value if it's under max
  if(currentValue < max)
  {
    fullArray = c(fullArray,currentValue)
    print(currentValue)
  }
}

# Keep only the even values
remainderArray = fullArray %% 2
fullArray = fullArray[remainderArray == 0]

# Calculate the sum
sum = sum(fullArray)
sum
